set(SIMULATION OFF CACHE BOOL "Include only simulation compatible tests")
set(RELEASE OFF CACHE BOOL "Performance optimized build")
set(VERIFICATION OFF CACHE BOOL "Only verification friendly kernel features")
set(SMP OFF CACHE BOOL "(if supported) Test SMP kernel")
set(NUM_NODES "" CACHE STRING "(if SMP) the number of nodes (default 4)")
set(PLATFORM "qemu-riscv-virt" CACHE STRING "Platform to test")
set(MCS OFF CACHE BOOL "MCS kernel")
set(UINTR OFF CACHE BOOL "(if supported) RISC-V uintr feature")
set(QEMU_BINARY "" CACHE STRING "Custom QEMU executable binary")
set(KernelSel4Arch "riscv64" CACHE STRING "aarch32, aarch64, arm_hyp, ia32, x86_64, riscv32, riscv64")
set(KernelRetypeFanOutLimit "512" CACHE STRING "")
